### ISSUE TITLE
[Question] What is meant by this line ?

### ISSUE THREAD

**Issue by acpmasquerade** [sagarchalise/picovico-python-sdk#4]
seeking answers.
? DEFAULT_SECTION_NAME = six.moves.configparser.DEFAULTSECT

**Comment by acpmasquerade** [comment]
section in profile file ?

if so, then we might need to use the word PROFILE instead of section. Each section means a separate PROFILE

**Comment by sagarchalise** [comment]
Yes it is the 'DEFAULT' term used by configparser for  section. In our case, it is default  profile.
